app = "crypto-poker-webapp"
primary_region = "waw"

[build]

[env]
PORT = "8080"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["app"]
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[processes]
app = "uvicorn server:app --host 0.0.0.0 --port 8080"
