app = "crypto-poker-webapp"

primary_region = "ams"

[build]
  python_version = "3.11.8"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[processes]
  app = "uvicorn server:app --host 0.0.0.0 --port 8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    timeout = "2s"

[checks]
  [checks.health]
    type = "http"
    interval = "15s"
    timeout = "5s"
    path = "/healthz"

[http_service]
  min_machines_running = 1
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

[deploy]
  strategy = "rolling"
